### ISSUE TITLE
ORWPT PTINQ issue - GT.M portability

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#126]
_CPRS issues a "cover sheet" RPC for every patient - top right box. JLV uses the same RPC. The RPC is ORWPT PTINQ._

... **Sent to Bhaskar/David**

But GT.M VISTA exceptions while Cache works. The problem line is https://github.com/OSEHRA-Sandbox/CodeConvergenceRegistration/blob/master/vxvista/DGRPD.m#L26

``` text
VISTA on GT.M (isolation) ...
OSEHRA>S DGSKIP="?42, ""From/To: """



OSEHRA>W @DGSKIP

%GTM-E-EXPR, Expression expected but not found

?42, "From/To: "


Cache shows ...

VISTA>S DGSKIP="?42, ""From/To: """



VISTA>W @DGSKIP

                                          From/To: 
```

**Comment by whitten** [comment]
By the way, this isn't a GT.M issue at all. The extra space is allowed in Cache because they changed the grammar they allowed, but GT.M uses Standard MUMPS, which does NOT allow the space.

So it would be more accurate to say the issue is ORWPT PTINQ issue - Non-standard MUMPS (Cacheism)

**Comment by whitten** [comment]
So basically the error is in this line:

https://github.com/OSEHRA-Sandbox/CodeConvergenceRegistration/blob/master/vxvista/DGRPD.m#L25

Where it says:
 N DGSKIP S DGSKIP=$S(DGFORGN:"!,?42,""From/To: """,1:"?42, ""From/To: """)

but should say:

 N DGSKIP S DGSKIP=$S(DGFORGN:"!,?42,""From/To: """,1:"?42,""From/To: """)

Since DGSKIP is used indirectly, no existing MUMPS system looks at contents of strings before it knows they have code in them. Personally, I would have coded:
 N DGSKIP S DGSKIP="?42,""From/To: """ S:DGFORGN DGSKIP="!,"_DGSKIP

It is less code and it shows more clearly that you only do linefeed if the DGFORGN variable is true.

Dave

**Comment by conorcaregraf** [comment]
Note added to setup
