### ISSUE TITLE
Prompts on command line from Allergy/TIU invocation

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#26]
__TODO FIRST__: isolate 2 calls that lead to prompts. See IO.

See: https://github.com/vistadataproject/VDM/blob/master/prototypes/vitals/rpcWriteVitals.js

Invoking the ALLERGY Create Call _EDITSAVE^ORWDAL32_ directly leads to "press return" prompts on the screen. Flows through [GMRAGUI1](https://github.com/OSEHRA/VistA-M/blob/master/Packages/Adverse%20Reaction%20Tracking/Routines/GMRAGUI1.m) ...

One ...

```text
CALL IRM AND HAVE USERS ASSIGNED TO THE GMRA MARK CHART MAIL GROUP
Enter RETURN to continue or '^' to exit: 
```

which comes from _W_ calls in [GMRASEND](https://github.com/OSEHRA/VistA-M/blob/master/Packages/Adverse%20Reaction%20Tracking/Routines/GMRASEND.m)

and then for "Observed Allergies", a progress note is created using ...

```text
D EN1^GMRAPET0(GMRADFN,.GMRAIEN,"S",.GMRAOUT)
```

and this brings up a shell with options to sign notes etc. - [GMRAPET0](https://github.com/OSEHRA/VistA-M/blob/master/Packages/Adverse%20Reaction%20Tracking/Routines/GMRAPET0.m)

__HOW TO BE SILENT?__ The RPC Broker must make a setting but how to do this explicitly?

**Comment by conorcaregraf** [comment]
## Debug Refs 

  * This - https://groups.google.com/forum/#!searchin/Hardhats/RPC$20Broker$20IO/hardhats/hM0ZOK7YKCI/7Op8YwjnPtQJ - gets into Allergies redirecting the Broker's reset of 
    * reference to text returned on RPC call (examine ie/ Q REPLY)
    * _normally, during RPC calls,  the IO channel is redircted to XWBNULL_ - _$IO_
  * D DEBUG^XWBTCPM (may not work in GT.M xinet.d forked broker as one per connection
  * $D(DIQUIET) - fileman setting
  * Cache: DO ^%STACK  --- VSHOW GT.M

**Comment by whitten** [comment]
Conor: minor typos.in in your notes:

Documented on http://www.vistapedia.com/index.php/DEBUG%5EXWBTCPM

To DEBUG a CPRS call from a terminal instead of RPC BROKER running in background
First create your CPRSCHART.EXE shortcut to have P=1234
something like:
CPRSChart.exe SERVER=192.168.1.1 SHOWRPCS PORT=1234

Second from inside MUMPS at a programmer command line:
MUMPS>D DEBUG^XWBTCPM

Before running this entry point set your debugger to stop at
the place you want to debug. Some spots to use:
'SERV+1^XWBTCPM', 'MAIN+1^XWBTCPM' or 'CAPI+1^XWBPRS.'

or location of your choice.

IP Socket to Listen on: 1234

rd: [XWB]
rd: 1030
rd: 4
rd:

rd: TCPConnect
CMD: TCPConnect
CMD: TCPConnect
rd: 5
rd: 0
rd: 012
rd: 192.1.1.127
rd: f
rd: 0
rd: 001
rd: 0
rd: f
rd: 0
rd: 017
rd: LAPTOP.WORLDVISTA.ORG
rd: f
rd:
wrt (9): accept
accept
accept
rd: [
rd: XWB]
rd: 1130
rd: 2
rd:
rd: 0
rd:
rd: XUS SIGNON SETUP
RPC: XUS SIGNON SETUP
RPC: XUS SIGNON SETUP
rd: 5
rd: 0
rd: 048
rd: 2-394203940231())(_)#%*!@#)(#_02934AJFOWAWPLSIER
rd: f
rd:
Call: SETUP^XUSRB(.XWBY,XWB(5,"P",0))
wrt (65): LAPTOP
EHR
EHR
/dev/pts/3
3
0
TEST.WORLDVISTA.ORG
1

rd: [
rd: XWB]
rd: 1130
rd: 2
rd:
rd: 0
rd:
rd: XUS INTRO MSG
RPC: XUS INTRO MSG
RPC: XUS INTRO MSG
rd: 5
rd: 4
rd: f
rd:
Call: INTRO^XUSRB(.XWBY)
wrt (174):                    TESTING ENVIRONMENT

               WorldVistA EHR /VOE 1.0

rd: [
rd: XWB]
rd: 1030
rd: 4
rd:
rd: #BYE#
CMD: #BYE#
CMD: #BYE#
rd:
wrt (8): #BYE#
BYE CMD
BYE CMD
Exit: #BYE#
Exit: #BYE#
Done

Next you had a typo:

Cache DO ^%STACK in GT.M is ZSHOW "S"

Both of these show the current call stack on your screen.

**Comment by whitten** [comment]
Did the DIQUIET work?
